title: DataSquad International Guide
description: This is a basic guide that lays out the mission, protocols, project guidelines, and professional development of members in the  DataSquad (DS) International!
theme: just-the-docs

url: https://datasquad-international.github.io/docs/

aux_links:
  Template Repository: https://github.com/DataSquad-International/docs
